


try{
	let b = 0;
	throw Error()
}catch(e){
	var a = 1;
}


console.log(a,e)